baseURL: https://yiyangyu.netlify.app
languageCode: en-us
title: Yiyang Yu
theme: PaperMod

header:
  show_logo: true
  show_search: true

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: timeline
      name: Timeline
      url: /timeline/
      weight: 30


params:
  homeInfoParams:
    Title: "Hi, I'm Yiyang"
    Content: Welcome to my blog. Currently under construction :) Aiming for a place where I can collate all my favourite learnings to share with others. 
  logo:
    - path: "/static/images/logo.png"
  socialIcons:
    - name: github
      url: "https://github.com/yiyangjessieyu"
    - name: linkedin
      url: "https://www.linkedin.com/in/yiyangjessieyu/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  # ShowShareButtons: true

  ShowPostNavLinks: true