baseURL: https://yiyangyu.netlify.app
languageCode: en-us
title: Yiyang Yu
#theme: PaperMod
theme: mini
paginate: 5
# cover: 
#   image: "static/images/logo.png"
#   hidden: true # only hide on current single page

# cover:
#   hidden: true # hide everywhere but not in structured data
#   hiddenInList: true # hide on list pages and home
#   hiddenInSingle: true # hide on single page


markup:
  highlight:
    guessSyntax: true
    style: emacs

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup# TODO
  # tableOfContents:
  #   endLevel: 3
  #   ordered: false
  #   startLevel: 2
  # # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  # goldmark:
  #   renderer:
  #     unsafe: true

header:
  show_logo: true
  show_search: true

menu:
  main:
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: timeline
      name: Timeline
      url: /timeline
      weight: 30


params:
  hiddenPostSummaryInHomePage: false
  copyright: By Yiyang Yu
  showPowerBy: false
  author: Yiyang Yu
  bio: 
  description: Currently under construction :) Repo for my messy notes and reflection. Aiming for a place where I can collate all my favourite learnings to share with others or my future self. 
  defaultTheme: auto # to switch between dark or light according to browser theme
  ShowWordCount: true
  homeInfoParams:
    Title: "Hi, I'm Yiyang"
    Content: Welcome to my blog. Currently under construction :) Repo for my messy notes and reflection. Aiming for a place where I can collate all my favourite learnings to share with others or my future self. 
  logo:
    - path: "/static/images/logo.png"
  socialIcons:
    - name: github
      url: "https://github.com/yiyangjessieyu"
    - name: linkedin
      url: "https://www.linkedin.com/in/yiyangjessieyu/"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  disableScrollToTop: false

  # ShowShareButtons: true

  ShowPostNavLinks: true

  outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search