baseURL: ""
languageCode: en-us
title: Yiyang Yu
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30


params:
  homeInfoParams:
    Title: "Hi, I'm Yiyang"
    Content: Welcome to my blog. Still a work in progress :) 
  logo:
    - path: "/static/images/logo.png"
  socialIcons:
    - name: github
      url: "https://github.com/yiyangjessieyu"
    - name: linkedin
      url: "https://www.linkedin.com/in/yiyangjessieyu/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  # ShowShareButtons: true

  ShowPostNavLinks: true